<?php

return [
        [
            'name' => 'Abia',
            'code' => 'ABI',
            'lga' => [
                ['name' => 'Aba North'],
                ['name' => 'Aba South'],
                ['name' => 'Arochukwu'],
                ['name' => 'Bende'],
                ['name' => 'Ikwuano'],
                ['name' => 'Isiala Ngwa North'],
                ['name' => 'Isiala Ngwa South'],
                ['name' => 'Isuikwuato'],
                ['name' => 'Obi Ngwa'],
                ['name' => 'Ohafia'],
                ['name' => 'Osisioma'],
                ['name' => 'Ugwunagbo'],
                ['name' => 'Ukwa East'],
                ['name' => 'Ukwa West'],
                ['name' => 'Umuahia North'],
                ['name' => 'Umuahia South'],
                ['name' => 'Umu Nneochi']
            ]
        ],
        [
            'name' => 'Adamawa',
            'code' => 'ADA',
            'lga' => [
                ['name' => 'Demsa'],
                ['name' => 'Fufure'],
                ['name' => 'Ganye'],
                ['name' => 'Gayuk'],
                ['name' => 'Gombi'],
                ['name' => 'Grie'],
                ['name' => 'Hong'],
                ['name' => 'Jada'],
                ['name' => 'Lamurde'],
                ['name' => 'Madagali'],
                ['name' => 'Maiha'],
                ['name' => 'Mayo Belwa'],
                ['name' => 'Michika'],
                ['name' => 'Mubi North'],
                ['name' => 'Mubi South'],
                ['name' => 'Numan'],
                ['name' => 'Shelleng'],
                ['name' => 'Song'],
                ['name' => 'Toungo'],
                ['name' => 'Yola North'],
                ['name' => 'Yola South'],

            ]
        ],
        [
            'name' => 'Akwa Ibom',
            'code' => 'AKI',
            'lga' => [
                ['name' => 'Abak',],
                ['name' => 'Eastern Obolo',],
                ['name' => 'Eket',],
                ['name' => 'Esit Eket',],
                ['name' => 'Essien Udim',],
                ['name' => 'Etim Ekpo',],
                ['name' => 'Etinan',],
                ['name' => 'Ibeno',],
                ['name' => 'Ibesikpo Asutan',],
                ['name' => 'Ibiono-Ibom',],
                ['name' => 'Ika',],
                ['name' => 'Ikono',],
                ['name' => 'Ikot Abasi',],
                ['name' => 'Ikot Ekpene',],
                ['name' => 'Ini',],
                ['name' => 'Itu',],
                ['name' => 'Mbo',],
                ['name' => 'Mkpat-Enin',],
                ['name' => 'Nsit-Atai',],
                ['name' => 'Nsit-Ibom',],
                ['name' => 'Nsit-Ubium',],
                ['name' => 'Obot Akara',],
                ['name' => 'Okobo',],
                ['name' => 'Onna',],
                ['name' => 'Oron',],
                ['name' => 'Oruk Anam',],
                ['name' => 'Udung-Uko',],
                ['name' => 'Ukanafun',],
                ['name' => 'Uruan',],
                ['name' => 'Urue-Offong/Oruko',],
                ['name' => 'Uyo',]

            ],
        ],
        [
            'name' => 'Anambra',
            'code' => 'ANA',
            'lga' => [
                ['name' => 'Aguata',],
                ['name' => 'Anambra East',],
                ['name' => 'Anambra West',],
                ['name' => 'Anaocha',],
                ['name' => 'Awka North',],
                ['name' => 'Awka South',],
                ['name' => 'Ayamelum',],
                ['name' => 'Dunukofia',],
                ['name' => 'Ekwusigo',],
                ['name' => 'Idemili North',],
                ['name' => 'Idemili South',],
                ['name' => 'Ihiala',],
                ['name' => 'Njikoka',],
                ['name' => 'Nnewi North',],
                ['name' => 'Nnewi South',],
                ['name' => 'Ogbaru',],
                ['name' => 'Onitsha North',],
                ['name' => 'Onitsha South',],
                ['name' => 'Orumba North',],
                ['name' => 'Orumba South',],
                ['name' => 'Oyi',],

            ]
        ],
        [
            'name' => 'Bauchi',
            'code' => 'BAU',
            'lga' => [
                ['name' => 'Alkaleri'],
                ['name' => 'Bauchi'],
                ['name' => 'Bogoro'],
                ['name' => 'Darazo'],
                ['name' => 'Dass'],
                ['name' => 'Gamawa'],
                ['name' => 'Ganjuwa'],
                ['name' => 'Giade'],
                ['name' => 'Jama`are'],
                ['name' => 'Katagum'],
                ['name' => 'Kirfi'],
                ['name' => 'Misau'],
                ['name' => 'Ningi'],
                ['name' => 'hira'],
                ['name' => 'Tafawa Balewa'],
                ['name' => 'Itas gadau'],
                ['name' => 'Toro'],
                ['name' => 'Warji'],
                ['name' => 'Zaki'],
                ['name' => 'Dambam']

            ]
        ],
        [
            'name' => 'Bayelsa',
            'code' => 'BAY',
            'lga' => [
                ['name' => 'Brass'],
                ['name' => 'Ekeremor'],
                ['name' => 'Kolok/Opokuma'],
                ['name' => 'Nembe'],
                ['name' => 'Ogbia'],
                ['name' => 'Sagbama'],
                ['name' => 'Southern Ijaw'],
                ['name' => 'Yenagoa'],
                ['name' => 'Membe']
            ]
        ],
        [
            'name' => 'Benue',
            'code' => 'BEN',
            'lga' => [

                ['name' => 'Ador'],
                ['name' => 'Agatu'],
                ['name' => 'Apa'],
                ['name' => 'Buruku'],
                ['name' => 'Gboko'],
                ['name' => 'Guma'],
                ['name' => 'Gwer east'],
                ['name' => 'Gwer west'],
                ['name' => 'Kastina'],
                ['name' => 'ala'],
                ['name' => 'Konshisha'],
                ['name' => 'Kwande'],
                ['name' => 'Logo'],
                ['name' => 'Makurdii'],
                ['name' => 'Obi'],
                ['name' => 'Ogbadibo'],
                ['name' => 'Ohimini'],
                ['name' => 'Oju'],
                ['name' => 'Okpokwu'],
                ['name' => 'Oturkpo'],
                ['name' => 'Tarka'],
                ['name' => 'Ukum'],
                ['name' => 'Vandekya']
            ]
        ],
        [
            'name' => 'Borno',
            'code' => 'BOR',
            'lga' => [
                ['name' => 'Abadan'],
                ['name' => 'Askira/Uba'],
                ['name' => 'Bama'],
                ['name' => 'Bayo'],
                ['name' => 'Biu'],
                ['name' => 'Chibok'],
                ['name' => 'Damboa'],
                ['name' => 'Dikwagubio'],
                ['name' => 'Guzamala'],
                ['name' => 'Gwoza'],
                ['name' => 'Hawul'],
                ['name' => 'Jere'],
                ['name' => 'Kaga'],
                ['name' => 'Kalka/Balge'],
                ['name' => 'Konduga'],
                ['name' => 'Kukawa'],
                ['name' => 'Kwaya-ku'],
                ['name' => 'Mafa'],
                ['name' => 'Magumeri'],
                ['name' => 'Maiduguri'],
                ['name' => 'Marte'],
                ['name' => 'Mobbar'],
                ['name' => 'Monguno'],
                ['name' => 'Ngala'],
                ['name' => 'Nganzai'],
                ['name' => 'Shani']
            ]
        ],
        [
            'name' => 'Cross River',
            'code' => 'CRS',
            'lga' => [
                ['name' => 'Abia'],
                ['name' => 'Akampa'],
                ['name' => 'Akpabuyo'],
                ['name' => 'Bakassi'],
                ['name' => 'Bekwara'],
                ['name' => 'Biase'],
                ['name' => 'Boki'],
                ['name' => 'Calabar south'],
                ['name' => 'Etung'],
                ['name' => 'Ikom'],
                ['name' => 'Obanliku'],
                ['name' => 'Obubra'],
                ['name' => 'Obudu'],
                ['name' => 'Odukpani'],
                ['name' => 'Ogoja'],
                ['name' => 'Ugep north'],
                ['name' => 'Yala'],
                ['name' => 'Yarkur']
            ]
        ],
        [
            'name' => 'Delta',
            'code' => 'DEL',
            'lga' => [
                ['name' => 'Aniocha south'],
                ['name' => 'Anioha'],
                ['name' => 'Bomadi'],
                ['name' => 'Burutu'],
                ['name' => 'Ethiope west'],
                ['name' => 'Ethiope east'],
                ['name' => 'Ika south'],
                ['name' => 'Ika north east'],
                ['name' => 'Isoko south'],
                ['name' => 'Isoko north'],
                ['name' => 'Ndokwa east'],
                ['name' => 'Ndokwa west'],
                ['name' => 'Okpe'],
                ['name' => 'Oshimili north'],
                ['name' => 'Oshimili south'],
                ['name' => 'Patani'],
                ['name' => 'Sapele'],
                ['name' => 'Udu'],
                ['name' => 'Ughelli south'],
                ['name' => 'Ughelli north'],
                ['name' => 'Ukwuani'],
                ['name' => 'Uviwie'],
                ['name' => 'Warri central'],
                ['name' => 'Warri north'],
                ['name' => 'Warri south']
            ]
        ],
        [
            'name' => 'Ebonyi',
            'code' => 'EBO',
            'lga' => [
                ['name' => 'Abakaliki'],
                ['name' => 'Afikpo south'],
                ['name' => 'Afikpo north'],
                ['name' => 'Ebonyi'],
                ['name' => 'Ezza'],
                ['name' => 'Ezza south'],
                ['name' => 'Ikwo'],
                ['name' => 'Ishielu'],
                ['name' => 'Ivo'],
                ['name' => 'Ohaozara'],
                ['name' => 'Ohaukwu'],
                ['name' => 'Onicha'],
                ['name' => 'Izzi']
            ]
        ],
        [
            'name' => 'Edo',
            'code' => 'EDO',
            'lga' => [
                ['name' => 'Akoko-Edo'],
                ['name' => 'Egor'],
                ['name' => 'Essann east'],
                ['name' => 'Esan south east'],
                ['name' => 'Esan central'],
                ['name' => 'Esan west'],
                ['name' => 'Etsako central'],
                ['name' => 'Etsako east'],
                ['name' => 'Etsako'],
                ['name' => 'Orhionwon'],
                ['name' => 'Ivia north'],
                ['name' => 'Ovia south west'],
                ['name' => 'Owan west'],
                ['name' => 'Owan south'],
                ['name' => 'Uhunwonde']
            ]
        ],
        [
            'name' => 'Ekiti',
            'code' => 'EKI',
            'lga' => [
                ['name' => 'Ado Ekiti'],
                ['name' => 'Effon Alaiye'],
                ['name' => 'Ekiti south west'],
                ['name' => 'Ekiti west'],
                ['name' => 'Ekiti east'],
                ['name' => 'Emure/ise'],
                ['name' => 'Orun'],
                ['name' => 'Ido'],
                ['name' => 'Osi'],
                ['name' => 'Ijero'],
                ['name' => 'Ikere'],
                ['name' => 'Ikole'],
                ['name' => 'Ilejemeje'],
                ['name' => 'Irepodun'],
                ['name' => 'Ise/Orun'],
                ['name' => 'Moba'],
                ['name' => 'Oye'],
                ['name' => 'Aiyekire']
            ]
        ],
        [
            'name' => 'Enugu',
            'code' => 'ENU',
            'lga' => [
                ['name' => 'Awgu'],
                ['name' => 'Aninri'],
                ['name' => 'Enugu east'],
                ['name' => 'Enugu south'],
                ['name' => 'Enugu north'],
                ['name' => 'Ezeagu'],
                ['name' => 'Igbo Eze north'],
                ['name' => 'Igbi etiti'],
                ['name' => 'Nsukka'],
                ['name' => 'Oji river'],
                ['name' => 'Undenu'],
                ['name' => 'Uzo Uwani'],
                ['name' => 'Udi']
            ]
        ],
        [
            'name' => 'Gombe',
            'code' => 'GOM',
            'lga' => [
                ['name' => 'kko'],
                ['name' => 'Balanga'],
                ['name' => 'Billiri'],
                ['name' => 'Dukku'],
                ['name' => 'Dunakaye'],
                ['name' => 'Gombe'],
                ['name' => 'Kaltungo'],
                ['name' => 'Kwami'],
                ['name' => 'Nafada/Bajoga'],
                ['name' => 'Shomgom'],
                ['name' => 'Yamaltu/Deba']
            ]
        ],
        [
            'name' => 'Imo',
            'code' => 'IMO',
            'lga' => [
                ['name' => 'Aboh-mbaise'],
                ['name' => 'Ahiazu-Mbaise'],
                ['name' => 'Ehime-Mbaino'],
                ['name' => 'Ezinhite'],
                ['name' => 'Ideato North'],
                ['name' => 'Ideato south'],
                ['name' => 'Ihitte/Uboma'],
                ['name' => 'Ikeduru'],
                ['name' => 'Isiala'],
                ['name' => 'Isu'],
                ['name' => 'Mbaitoli'],
                ['name' => 'Ngor Okpala'],
                ['name' => 'Njaba'],
                ['name' => 'Nwangele'],
                ['name' => 'Nkwere'],
                ['name' => 'Obowo'],
                ['name' => 'Aguta'],
                ['name' => 'Ohaji Egbema'],
                ['name' => 'Okigwe'],
                ['name' => 'Onuimo'],
                ['name' => 'Orlu'],
                ['name' => 'Orsu'],
                ['name' => 'Oru west'],
                ['name' => 'Oru'],
                ['name' => 'Owerri'],
                ['name' => 'Owerri North'],
                ['name' => 'Owerri south']
            ]
        ],
        [
            'name' => 'Jigawa',
            'code' => 'JIG',
            'lga' => [
                ['name' => 'Auyo'],
                ['name' => 'Babura'],
                ['name' => 'Birnin- Kudu'],
                ['name' => 'Birniwa'],
                ['name' => 'Buji'],
                ['name' => 'Dute'],
                ['name' => 'Garki'],
                ['name' => 'Gagarawa'],
                ['name' => 'Gumel'],
                ['name' => 'Guri'],
                ['name' => 'Gwaram'],
                ['name' => 'Gwiwa'],
                ['name' => 'Hadeji'],
                ['name' => 'Jahun'],
                ['name' => 'Kafin-Hausa'],
                ['name' => 'kaugama'],
                ['name' => 'Kazaure'],
                ['name' => 'Kirikisamma'],
                ['name' => 'Birnin-magaji'],
                ['name' => 'Maigatari'],
                ['name' => 'Malamaduri'],
                ['name' => 'Miga'],
                ['name' => 'Ringim'],
                ['name' => 'Roni'],
                ['name' => 'Sule Tankarka'],
                ['name' => 'Taura'],
                ['name' => 'Yankwasi']
            ]
        ],
        [
            'name' => 'Abuja',
            'code' => 'FCT',
            'lga' => [
                ['name' => 'Abaji'],
                ['name' => 'Abuja Municipal'],
                ['name' => 'Bwari'],
                ['name' => 'Gwagwalada'],
                ['name' => 'Kuje'],
                ['name' => 'Kwali']

            ]
        ],
        [
            'name' => 'Kaduna',
            'code' => 'KAD',
            'lga' => [
                ['name' => 'Brnin Gwari'],
                ['name' => 'Chukun'],
                ['name' => 'Giwa'],
                ['name' => 'Kajuru'],
                ['name' => 'Igabi'],
                ['name' => 'Ikara'],
                ['name' => 'Jaba'],
                ['name' => 'Jema`a'],
                ['name' => 'Kachia'],
                ['name' => 'Kaduna North'],
                ['name' => 'Kaduna south'],
                ['name' => 'Kagarok'],
                ['name' => 'Kauru'],
                ['name' => 'Kabau'],
                ['name' => 'Kudan'],
                ['name' => 'Kere'],
                ['name' => 'Makarfi'],
                ['name' => 'Sabongari'],
                ['name' => 'Sanga'],
                ['name' => 'Soba'],
                ['name' => 'Zangon-Kataf'],
                ['name' => 'Zaria']
            ]
        ],
        [
            'name' => 'Kano',
            'code' => 'KAN',
            'lga' => [
                ['name' => 'Ajigi'],
                ['name' => 'Albasu'],
                ['name' => 'Bagwai'],
                ['name' => 'Bebeji'],
                ['name' => 'Bichi'],
                ['name' => 'Bunkure'],
                ['name' => 'Dala'],
                ['name' => 'Dambatta'],
                ['name' => 'Dawakin kudu'],
                ['name' => 'Dawakin tofa'],
                ['name' => 'doguwa'],
                ['name' => 'Fagge'],
                ['name' => 'Gabasawa'],
                ['name' => 'Garko'],
                ['name' => 'Garun mallam'],
                ['name' => 'Gaya'],
                ['name' => 'Gezawa'],
                ['name' => 'Gwale'],
                ['name' => 'Gwarzo'],
                ['name' => 'Kano'],
                ['name' => 'Karay'],
                ['name' => 'Kibiya'],
                ['name' => 'Kiru'],
                ['name' => 'Kumbtso'],
                ['name' => 'Kunch'],
                ['name' => 'Kura'],
                ['name' => 'Maidobi'],
                ['name' => 'Makoda'],
                ['name' => 'MInjibir Nassarawa'],
                ['name' => 'Rano'],
                ['name' => 'Rimin gado'],
                ['name' => 'Rogo'],
                ['name' => 'Shanono'],
                ['name' => 'Sumaila'],
                ['name' => 'Takai'],
                ['name' => 'Tarauni'],
                ['name' => 'Tofa'],
                ['name' => 'Tsanyawa'],
                ['name' => 'Tudunwada'],
                ['name' => 'Ungogo'],
                ['name' => 'Warawa'],
                ['name' => 'Wudil']
            ]
        ],
        [
            'name' => 'Katsina',
            'code' => 'KAT',
            'lga' => [
                ['name' => 'Bakori'],
                ['name' => 'Batagarawa'],
                ['name' => 'Batsari'],
                ['name' => 'Baure'],
                ['name' => 'Bindawa'],
                ['name' => 'Charanchi'],
                ['name' => 'Dan- Musa'],
                ['name' => 'Dandume'],
                ['name' => 'Danja'],
                ['name' => 'Daura'],
                ['name' => 'Dutsi'],
                ['name' => 'Dutsin `ma'],
                ['name' => 'Faskar'],
                ['name' => 'Funtua'],
                ['name' => 'Ingawa'],
                ['name' => 'Jibiya'],
                ['name' => 'Kafur'],
                ['name' => 'Kaita'],
                ['name' => 'Kankara'],
                ['name' => 'Kankiya'],
                ['name' => 'Katsina'],
                ['name' => 'Furfi'],
                ['name' => 'Kusada.Mai aduwa'],
                ['name' => 'Malumfashi'],
                ['name' => 'Mani'],
                ['name' => 'Mash'],
                ['name' => 'Matazu'],
                ['name' => 'Musawa'],
                ['name' => 'Rimi'],
                ['name' => 'Sabuwa'],
                ['name' => 'Safana'],
                ['name' => 'Sandamu'],
                ['name' => 'Zango']
            ]
        ],
        [
            'name' => 'Kebbi',
            'code' => 'KEB',
            'lga' => [
                ['name' => 'Aliero'],
                ['name' => 'Arewa Dandi'],
                ['name' => 'Argungu'],
                ['name' => 'Augie'],
                ['name' => 'Bagudo'],
                ['name' => 'Birnin Kebbi'],
                ['name' => 'Bunza'],
                ['name' => 'Dandi'],
                ['name' => 'Danko'],
                ['name' => 'Fakai'],
                ['name' => 'Gwandu'],
                ['name' => 'Jeda'],
                ['name' => 'Kalgo'],
                ['name' => 'Koko-besse'],
                ['name' => 'Maiyaama'],
                ['name' => 'Ngaski'],
                ['name' => 'Sakaba'],
                ['name' => 'Shanga'],
                ['name' => 'Suru'],
                ['name' => 'Wasugu'],
                ['name' => 'Yauri'],
                ['name' => 'Zuru']
            ]
        ],
        [
            'name' => 'Kogi',
            'code' => 'KOG',
            'lga' => [
                ['name' => 'Adavi'],
                ['name' => 'Ajaokuta'],
                ['name' => 'Ankpa'],
                ['name' => 'Bassa'],
                ['name' => 'Dekina'],
                ['name' => 'Yagba east'],
                ['name' => 'Ibaji'],
                ['name' => 'Idah'],
                ['name' => 'Igalamela'],
                ['name' => 'Ijumu'],
                ['name' => 'Kabba bunu'],
                ['name' => 'Kogi'],
                ['name' => 'Mopa muro'],
                ['name' => 'Ofu'],
                ['name' => 'Ogori magongo'],
                ['name' => 'Okehi'],
                ['name' => 'Okene'],
                ['name' => 'Olamaboro'],
                ['name' => 'Omala'],
                ['name' => 'Yagba west']
            ]
        ],
        [
            'name' => 'Kwara',
            'code' => 'KWA',
            'lga' => [
                ['name' => 'Asa'],
                ['name' => 'Baruten'],
                ['name' => 'Ede'],
                ['name' => 'Ekiti'],
                ['name' => 'Ifelodun'],
                ['name' => 'Ilorin south'],
                ['name' => 'Ilorin west'],
                ['name' => 'Ilorin east'],
                ['name' => 'Irepodun'],
                ['name' => 'Isin'],
                ['name' => 'Kaiama'],
                ['name' => 'Moro'],
                ['name' => 'Offa'],
                ['name' => 'Oke ero'],
                ['name' => 'Oyun'],
                ['name' => 'Pateg']
            ]
        ],
        [
            'name' => 'Lagos',
            'code' => 'LAG',
            'lga' => [
                ['name' => 'Agege'],
                ['name' => 'Alimosho Ifelodun'],
                ['name' => 'Alimosho'],
                ['name' => 'Amuwo-Odofin'],
                ['name' => 'Apapa'],
                ['name' => 'Badagry'],
                ['name' => 'Epe'],
                ['name' => 'Eti-Osa'],
                ['name' => 'Ibeju-Lekki'],
                ['name' => 'Ifako/Ijaye'],
                ['name' => 'Ikeja'],
                ['name' => 'Ikorodu'],
                ['name' => 'Kosofe'],
                ['name' => 'Lagos Island'],
                ['name' => 'Lagos Mainland'],
                ['name' => 'Mushin'],
                ['name' => 'Ojo'],
                ['name' => 'Oshodi-Isolo'],
                ['name' => 'Shomolu'],
                ['name' => 'Surulere']
            ]
        ],
        [
            'name' => 'Nasarawa',
            'code' => 'NAS',
            'lga' => [
                ['name' => 'Akwanga'],
                ['name' => 'Awe'],
                ['name' => 'Doma'],
                ['name' => 'Karu'],
                ['name' => 'Keana'],
                ['name' => 'Keffi'],
                ['name' => 'Kokona'],
                ['name' => 'Lafia'],
                ['name' => 'Nassarawa'],
                ['name' => 'Nassarawa/Eggon'],
                ['name' => 'Obi'],
                ['name' => 'Toto'],
                ['name' => 'Wamba']
            ]
        ],
        [
            'name' => 'Niger',
            'code' => 'NIG',
            'lga' => [
                ['name' => 'Agaie'],
                ['name' => 'Agwara'],
                ['name' => 'Bida'],
                ['name' => 'Borgu'],
                ['name' => 'Bosso'],
                ['name' => 'Chanchanga'],
                ['name' => 'Edati'],
                ['name' => 'Gbako'],
                ['name' => 'Gurara'],
                ['name' => 'Kitcha'],
                ['name' => 'Kontagora'],
                ['name' => 'Lapai'],
                ['name' => 'Lavun'],
                ['name' => 'Magama'],
                ['name' => 'Mariga'],
                ['name' => 'Mokwa'],
                ['name' => 'Moshegu'],
                ['name' => 'Muya'],
                ['name' => 'Paiko'],
                ['name' => 'Rafi'],
                ['name' => 'Shiroro'],
                ['name' => 'Suleija'],
                ['name' => 'Tawa-Wushishi']
            ]
        ],
        [
            'name' => 'Ogun',
            'code' => 'OGU',
            'lga' => [
                ['name' => 'Abeokuta south'],
                ['name' => 'Abeokuta north'],
                ['name' => 'Ado-odo/otta'],
                ['name' => 'Ewekoro'],
                ['name' => 'Ifo'],
                ['name' => 'Ijebu east'],
                ['name' => 'Ijebu north'],
                ['name' => 'Ijebu ode'],
                ['name' => 'Ikenne'],
                ['name' => 'Imeko afon'],
                ['name' => 'Ipokia'],
                ['name' => 'Obafemi/owode'],
                ['name' => 'Egbado North'],
                ['name' => 'Egbado south'],
                ['name' => 'Odogbolu'],
                ['name' => 'Ogun waterside'],
                ['name' => 'Remo North'],
                ['name' => 'Yewa  North'],
                ['name' => 'Yewa  South'],
                ['name' => 'Sagamu']
            ]
        ],
        [
            'name' => 'Ondo',
            'code' => 'OND',
            'lga' => [
                ['name' => 'Akoko north'],
                ['name' => 'Akoko north east'],
                ['name' => 'Akoko south east'],
                ['name' => 'Akoko south'],
                ['name' => 'Akure north'],
                ['name' => 'Akure'],
                ['name' => 'Idanre'],
                ['name' => 'Ifedore'],
                ['name' => 'Ese odo'],
                ['name' => 'Ilaje'],
                ['name' => 'Ilaje oke-igbo'],
                ['name' => 'Irele'],
                ['name' => 'Odigbo'],
                ['name' => 'Okitipupa'],
                ['name' => 'Ondo'],
                ['name' => 'Ondo east'],
                ['name' => 'Ose'],
                ['name' => 'Owo']
            ]
        ],
        [
            'name' => 'Osun',
            'code' => 'OSU',
            'lga' => [
                ['name' => 'Atakumosa west'],
                ['name' => 'Atakumosa east'],
                ['name' => 'Ayeda-ade'],
                ['name' => 'Ayedire'],
                ['name' => 'Bolawaduro'],
                ['name' => 'Boripe'],
                ['name' => 'Ede'],
                ['name' => 'Ede north'],
                ['name' => 'Egbedore'],
                ['name' => 'Ejigbo'],
                ['name' => 'Ife north'],
                ['name' => 'Ife central'],
                ['name' => 'Ife south'],
                ['name' => 'Ife east'],
                ['name' => 'Ifedayo'],
                ['name' => 'Ifelodun'],
                ['name' => 'Ilesha west'],
                ['name' => 'Ila- orangun'],
                ['name' => 'Ilesah east'],
                ['name' => 'Irepodun'],
                ['name' => 'Irewole'],
                ['name' => 'Isokan'],
                ['name' => 'Iwo'],
                ['name' => 'Obokun'],
                ['name' => 'Odo-otin'],
                ['name' => 'ola oluwa'],
                ['name' => 'olorunda'],
                ['name' => 'Oriade'],
                ['name' => 'Orolu'],
                ['name' => 'Osogbo']
            ]
        ],
        [
            'name' => 'Oyo',
            'code' => 'OYO',
            'lga' => [
                ['name' => 'Afijio'],
                ['name' => 'Akinyele'],
                ['name' => 'Attba'],
                ['name' => 'Atigbo'],
                ['name' => 'Egbeda'],
                ['name' => 'Ibadan north east'],
                ['name' => 'Ibadan central'],
                ['name' => 'Ibadan south east'],
                ['name' => 'Ibadan west south'],
                ['name' => 'Ibarapa east'],
                ['name' => 'Ibarapa north'],
                ['name' => 'Ido'],
                ['name' => 'Ifedapo'],
                ['name' => 'Ifeloju'],
                ['name' => 'Irepo'],
                ['name' => 'Iseyin'],
                ['name' => 'Itesiwaju'],
                ['name' => 'Iwajowa'],
                ['name' => 'Iwajowa olorunshogo'],
                ['name' => 'Kajola'],
                ['name' => 'Lagelu'],
                ['name' => 'Ogbomosho north'],
                ['name' => 'Ogbomosho south'],
                ['name' => 'Ogo oluwa'],
                ['name' => 'Oluyole'],
                ['name' => 'Ona ara'],
                ['name' => 'Ore lope'],
                ['name' => 'Orire'],
                ['name' => 'Oyo east'],
                ['name' => 'Oyo west'],
                ['name' => 'Saki east'],
                ['name' => 'Saki west'],
                ['name' => 'Surulere']
            ]
        ],
        [
            'name' => 'Plateau',
            'code' => 'PLA',
            'lga' => [
                ['name' => 'Barkin/ladi'],
                ['name' => 'Bassa'],
                ['name' => 'Bokkos'],
                ['name' => 'Jos'],
                ['name' => 'north'],
                ['name' => 'Jos east'],
                ['name' => 'Jos south'],
                ['name' => 'Kanam'],
                ['name' => 'kiyom'],
                ['name' => 'Langtang north Langtang south'],
                ['name' => 'Mangu'],
                ['name' => 'Mikang'],
                ['name' => 'Pankshin'],
                ['name' => 'Qua`an pan'],
                ['name' => 'Shendam'],
                ['name' => 'Wase']
            ]
        ],
        [
            'name' => 'Rivers',
            'code' => 'RIV',
            'lga' => [
                ['name' => 'Abua/Odial'],
                ['name' => 'Ahoada west'],
                ['name' => 'Akuku toru'],
                ['name' => 'Andoni'],
                ['name' => 'Asari toru'],
                ['name' => 'Bonny'],
                ['name' => 'Degema'],
                ['name' => 'Eleme'],
                ['name' => 'Emohua'],
                ['name' => 'Etche'],
                ['name' => 'Gokana'],
                ['name' => 'Ikwerre'],
                ['name' => 'Oyigbo'],
                ['name' => 'Khana'],
                ['name' => 'Obio/Akpor'],
                ['name' => 'Ogba east /Edoni'],
                ['name' => 'Ogu/bolo'],
                ['name' => 'Okrika'],
                ['name' => 'Omumma'],
                ['name' => 'Opobo/Nkoro'],
                ['name' => 'Portharcourt'],
                ['name' => 'Tai']
            ]
        ],
        [
            'name' => 'Sokoto',
            'code' => 'SOK',
            'lga' => [
                ['name' => 'Binji'],
                ['name' => 'Bodinga'],
                ['name' => 'Dange/shuni'],
                ['name' => 'Gada'],
                ['name' => 'Goronyo'],
                ['name' => 'Gudu'],
                ['name' => 'Gwadabawa'],
                ['name' => 'Illella'],
                ['name' => 'Kebbe'],
                ['name' => 'Kware'],
                ['name' => 'Rabah'],
                ['name' => 'Sabon-Birni'],
                ['name' => 'Shagari'],
                ['name' => 'Silame'],
                ['name' => 'Sokoto south'],
                ['name' => 'Sokoto north'],
                ['name' => 'Tambuwal'],
                ['name' => 'Tangaza'],
                ['name' => 'Tureta'],
                ['name' => 'Wamakko'],
                ['name' => 'Wurno'],
                ['name' => 'Yabo']
            ]
        ],
        [
            'name' => 'Taraba',
            'code' => 'TAR',
            'lga' => [
                ['name' => 'Akdo-kola'],
                ['name' => 'Bali'],
                ['name' => 'Donga'],
                ['name' => 'Gashaka'],
                ['name' => 'Gassol'],
                ['name' => 'Ibi'],
                ['name' => 'Jalingo'],
                ['name' => 'K/Lamido'],
                ['name' => 'Kurmi'],
                ['name' => 'lan'],
                ['name' => 'Sardauna'],
                ['name' => 'Tarum'],
                ['name' => 'Ussa'],
                ['name' => 'Wukari'],
                ['name' => 'Yorro'],
                ['name' => 'Zing']
            ]
        ],
        [
            'name' => 'Yobe',
            'code' => 'YOB',
            'lga' => [
                ['name' => 'Borsari'],
                ['name' => 'Damaturu'],
                ['name' => 'Fika'],
                ['name' => 'Fune'],
                ['name' => 'Geidam'],
                ['name' => 'Gogaram'],
                ['name' => 'Gujba'],
                ['name' => 'Gulani'],
                ['name' => 'Jakusko'],
                ['name' => 'Karasuwa'],
                ['name' => 'Machina'],
                ['name' => 'Nagere'],
                ['name' => 'Nguru'],
                ['name' => 'Potiskum'],
                ['name' => 'Tarmua'],
                ['name' => 'Yunusari'],
                ['name' => 'Yusufari'],
                ['name' => 'G ashua']

            ]
        ],
        [
            'name' => 'Zamfara',
            'code' => 'ZAM',
            'lga' => [
                ['name' => 'Anka'],
                ['name' => 'bukkuyum'],
                ['name' => 'Dungudu'],
                ['name' => 'Chafe'],
                ['name' => 'Gummi'],
                ['name' => 'Gusau'],
                ['name' => 'Isa'],
                ['name' => 'Kaura/Namoda'],
                ['name' => 'Mradun'],
                ['name' => 'Maru'],
                ['name' => 'Shinkafi'],
                ['name' => 'Talata/Mafara'],
                ['name' => 'Zumi']


            ]
        ]
    ];
