<?php


namespace App\Swagger\Models;

use Swagger\Annotations as SWG;

/**
 * @property int status
 * @SWG\Definition(
 *      definition="CreateVerificationRequest",
 *      required={"code", "parent_agent_id", "date", "type"},
 *      @SWG\Property(
 *          property="code",
 *          description="agent code",
 *          type="string",
 *      ),
 *      @SWG\Property(
 *          property="parent_agent_id",
 *          description="Parent agent id|code",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="territory_id",
 *          description="territory id",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="device_owner_id",
 *          description="device owner id",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="date",
 *          description="date",
 *          type="string",
 *          format="date"
 *      ),
 *      @SWG\Property(
 *          property="type",
 *          description="principal agent, sole agent",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="is_app_only",
 *          description="0=No,1=Yes",
 *          type="boolean"
 *      ),
 *      @SWG\Property(
 *          property="first_name",
 *          description="first_name",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="last_name",
 *          description="last_name",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="user_name",
 *          description="user_name",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="gender",
 *          description="Male, Female",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="date_of_birth",
 *          description="date_of_birth",
 *          type="string",
 *          format="date"
 *      ),
 *      @SWG\Property(
 *          property="passport",
 *          description="passport",
 *          type="string"
 *      ),
 *     @SWG\Property(
 *          property="personal_information",
 *          type="object",
 *          @SWG\Property(
 *              property="email",
 *              description="email",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="phone_number",
 *              description="phone_number",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="phone_number2",
 *              description="phone_number2",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="imei",
 *              description="imei",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="bvn",
 *              description="bvn",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="bank_account_name",
 *              description="bank_account_name",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="bank_account_number",
 *              description="bank_account_number",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="product_of_interest",
 *              description="Money Transfer/Withdrawal Bill Payment Gaming ",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="designation",
 *              description="Principal Agent, Sole Agent",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="occupation",
 *              description="Profession/Occupation",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="home_address",
 *              description="home_address",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="outlet_address",
 *              description="outlet_address",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="outlet_type",
 *              description="Shop,Office,Kiosk,Umbrella,Mobile,Others ",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="landmark",
 *              description="landmark",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="lga_id",
 *              description="lga_id",
 *              type="integer",
 *              format="int32"
 *          ),
 *          @SWG\Property(
 *              property="state_id",
 *              description="state_id",
 *              type="integer",
 *              format="int32"
 *          ),
 *          @SWG\Property(
 *              property="latitude",
 *              description="latitude",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="name_of_acquirer",
 *              description="Name of Acquirer/TP",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="android_phone",
 *              description="0=No, 1=Yes",
 *              type="boolean"
 *          ),
 *          @SWG\Property(
 *              property="bluetooth_printer",
 *              description="0=No, 1=Yes",
 *              type="boolean"
 *          ),
 *          @SWG\Property(
 *              property="signature",
 *              description="signature",
 *              type="string"
 *          )
 *     ),
 *      @SWG\Property(
 *          property="guarantor_information",
 *          type="object",
 *          required={"verification_id","full_name","occupation","business_name","office_address","position","department","telephone_number","email","residential_address","mobile_number","relationship","no_of_relations_ship_years","signature","witness_signature","witness_full_name","witness_occupation","witness__address","witness_telephone_number","witness_email"},
 *          @SWG\Property(
 *              property="full_name",
 *              description="full_name",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="occupation",
 *              description="Profession/Occupation",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="business_name",
 *              description="Business/Office Name",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="office_address",
 *              description="office_address",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="position",
 *              description="Position/Status",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="department",
 *              description="Deparment or Unit",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="telephone_number",
 *              description="telephone_number",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="email",
 *              description="email",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="residential_address",
 *              description="residential_address",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="mobile_number",
 *              description="mobile_number",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="relationship",
 *              description="Relationship to the Applicant:",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="no_of_relations_ship_years",
 *              description="Number of Years you have known the applicant?",
 *              type="integer",
 *              format="int32"
 *          ),
 *          @SWG\Property(
 *              property="signature",
 *              description="signature",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="witness_signature",
 *              description="witness_signature",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="witness_full_name",
 *              description="witness_full_name",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="witness_occupation",
 *              description="Profession/Occupation",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="witness__address",
 *              description="witness__address",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="witness_telephone_number",
 *              description="witness_telephone_number",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="witness_email",
 *              description="witness_email",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="created_at",
 *              description="created_at",
 *              type="string",
 *              format="date-time"
 *          ),
 *          @SWG\Property(
 *              property="updated_at",
 *              description="updated_at",
 *              type="string",
 *              format="date-time"
 *          )
 *      )
 * )
 */
class CreateVerificationRequest
{

}